# Change these first
owner: MatBenfield # Your GitHub username
repo: up # Your Github repository name

# Add your sites here
sites:
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Secret Site
    url: $SECRET_SITE
assignees: # Users to assign downtime issues (optional)
  - MatBenfield
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: dev.thechels.uk
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Up** is an open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: "message"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
