# Change these first
owner: MatBenfield # Your GitHub username
repo: up # Your Github repository name

# Add your sites here
sites:
  - name: Morning
    url: https://morning.thechels.uk
  - name: toCFCws
    url: https://app.thechels.uk
  - name: Blog
    url: https://thechels.uk
  - name: Finances
    url: https://finances.thechels.uk
  - name: Horoscopes
    url: https://horofootball.thechels.uk
  - name: Crisis
    url: https://isthereacrisis.thechels.uk 
assignees: # Users to assign downtime issues (optional)
  - MatBenfield
status-website:
  cname: dev.thechels.uk
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Up** is an open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: "message"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
